### ISSUE TITLE
Debian 10.3 : nl802145 not found

### ISSUE THREAD

**Issue by dpapdpap** [linux-wpan/wpan-tools#20]
Hi
I'm new in linux and I have setup a VMware machine with Debian 10.3.
I install wpan-tools with these commands (acording to https://github.com/RIOT-Makers/wpan-raspbian/wiki/Create-a-generic-Raspbian-image-with-6LoWPAN-support#4-new-linux-kernels-for-the-pi)
`sudo apt install device-tree-compiler`
`sudo dtc -@ -O dtb -o mrf24j40ma.dtbo mrf24j40ma-overlay.dts`
In **Rasbian** I append `dtoverlay=mrf24j40ma` to file **/boot/config.txt**
**after reboot i execute**
`sudo apt install git`
`sudo mkdir /opt/src`
`sudo chown pi /opt/src`
`cd /opt/src`
`git clone https://github.com/linux-wpan/wpan-tools`
`sudo apt install dh-autoreconf  libnl-3-dev libnl-genl-3-dev libnl-route-3-dev`
`cd /opt/src/wpan-tools`
`./autogen.sh`
`./configure CFLAGS='-g -O0' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib`
`make`
`sudo make install`
but when i execute `iwpan list` i receive the message **`nl802154 not found`**
I have done the same at Raspberry Pi 3 B+ and it works 
But in Debian there isn't  /boot/config.txt to append
How can I solve the  **`nl802154 not found`** problem please ?

**Comment by alexaring** [comment]
ieee802154 module is not loaded. Something is not working in your setup check if mrf24j40ma module is actually being loaded.

**Comment by dpapdpap** [comment]
Thanks for your reply.
I install Ubuntu 16.04 without mrf24j40ma and it doesn't complaint for nl802154. Contiki runs ok.
That makes me suppose that is something in Debian.
However, how can i check if mrf24j40ma is installed in Debian ?
Thanks again

**Comment by alexaring** [comment]
run lsmod.

Try also modprobe mac802154_hwsim, this is a virtual driver and you should see some virtual phy's at least. I cannot help you with your devicetree setup.

**Comment by dpapdpap** [comment]
I'll try it.
Thanks again

**Comment by dpapdpap** [comment]
Indeed, it does not appear to have been installed.
I tried modprobe mac802154_hwsim and with iwpan list I can see some phy's.
You are very kind, thanks for the help

**Comment by alexaring** [comment]
Sorry, I am pretty sure it is installed but somehow your devicetree setup is not working to match properly. Try modprobe mrf24j40ma, you will see. This issue is out of scope of linuw-wpan.

**Comment by dpapdpap** [comment]
sudo modprobe mrf24j40ma gives "modprobe: FATAL: Module mrf24j40ma not found in directory /lib/modules/4.19.0-8-amd64"
I have done what is suggested [here](https://github.com/RIOT-Makers/wpan-raspbian/wiki/Create-a-generic-Raspbian-image-with-6LoWPAN-support#4-new-linux-kernels-for-the-pi)
At raspberry Pi 3B+ it works fine but not in vmware's Debian 10

**Comment by alexaring** [comment]
This is simple because vmware doesn't support any kind of SPI bus communication so far I know. You connecting things here which are impossible to connect. Do you research better please.
