### ISSUE TITLE
wpan-tools for WPAN network built over OpenThread 

### ISSUE THREAD

**Issue by sohaibbinaltaf** [linux-wpan/wpan-tools#22]
I have built a thread network using raspberry pi 4B and Nordic nRF52840 dongle. Can I use wpan-tools in this setup to get network performance information? Is there any tutorial availble which I can follow to install wpan-tools over my thread device?

**Comment by Stefan-Schmidt** [comment]
wpan-tools are used to configure the Linux in-kernel ieee802154 stack. OpenThread does not use this stack, but has its own implementation of the relevant parts. For any configuration of your OpenThread device you should look at the ot-ctl commands coming with the OT project.

Having OpenThread running over the in-kernel ieee802154 stack is something we think about and have ideas on, but it is not ready. It needs more support on the kernel side as well as development of a native linux platform for OT.

**Comment by sohaibbinaltaf** [comment]
Thank you
