### ISSUE TITLE
Include some basic socket example with wpan-tools to help people using linux-wpan with and without 6LoWPAN

### ISSUE THREAD

**Issue by Stefan-Schmidt** [linux-wpan/wpan-tools#3]
The idea would be to have an example directory inside wpan-tools which contains basic API examples for the following:
- Get attributes from the netlink interface
- Usage of the socket API for plain ieee802154 sockets
  o Usage of the socket API for 6LoWPAN usage

**Comment by alexaring** [comment]
I would remove the current socket api and replace it with a new one.

Above this new socket api for ngaf802154 we should make some examples. Then later replace ngaf802154 with af802154.

**Comment by zmingshi** [comment]
Hi, all

I'm using wpan-ping.c to make the two at86rf233 modules communicate periodically (every 120ms). I record some timestamps on wpan-ping client side. The timestamps include send_timestamp, start_timestamp and end_timestamp. 
  send_timestamp means the time before sending the packet
  start_timestamp means the time just after sending the packet
  end_timestamp has two meanings. When in receiving success case, it means the time just after receiving the packet; When in timeout case, it means the time after the receiving time runs out (in my case, timeout value is set to 120ms)
  Also, in the receiving success case, usleep() function is applied to make sure the period is 120ms 

I find some problems when analyzing the timestamps:
1. when in timeout case, I find there are some records in which the difference between end_timesatmp and send_timestamp is far greater than 120, some even reach over 1000 (start_timestamp-send_timestamp~=0). In this case, I doubt if there is something wrong with the function of receiving timeout?
2. when in receiving success case, there are also a few records in which the difference between current send_timestamp and next send_timestamp is far greater than 120. I have checked the difference value: start_timestamp-send_timestamp~=0, end_timestamp-start_timestamp=rtt. Also, send_timestamp(next)-send_timestamp(current)~=send_timestamp(next)-end_timestamp(current). During the period between end_timestamp(current) and send_timestamp(next), logging function, usleep() and generate_packet() functions are executed. logging function means to open a file and write the timestamp like values into the file. I have also checked the sleeping time, it's right. In this case, I'm not sure what is wrong with the procedure.

Sorry for so long an issue, hope you could be patient to read it, also hope you could give some suggestions, thank you all!

**Comment by Stefan-Schmidt** [comment]
@zmingshi why are you using this issue about wpan socket examples for a complete different issue?

This is not a discussion forum but an issue tracker. If you want to discuss changes to wpan-ping.c use the mailing list and show the source code of your modifications.
http://vger.kernel.org/vger-lists.html#linux-wpan

**Comment by zmingshi** [comment]
@Stefan-Schmidt sorry for that, I'll delete my question soon. Actually, I have joined the mailing list using my gmail, but I can not access the gmail in my working place. And, I use the outlook email in the working place, but I cannot join the mailing list with my outlook, I don't know why.
Sorry for that again!

**Comment by Stefan-Schmidt** [comment]
A set of examples for the socket API has been merged in master today. The examples folder holds them and can hold further examples in the future if needed.
