### ISSUE TITLE
fix release 0.5.1

### ISSUE THREAD

**Issue by alexaring** [linux-wpan/wpan-tools#9]
newer libnl fails to build.

We need a fix release with:
https://github.com/linux-wpan/wpan-tools/commit/51ab69d76aa708c79aed971ee4083abb8cc07201

included.

**Comment by Stefan-Schmidt** [comment]
Do we want a 0.5.1 with only this patch or should we just do a 0.6 with this one and all the other things included? Looking over them they all look like bug fixes.

I can do a release next week.

**Comment by alexaring** [comment]
make it so.

**Comment by Stefan-Schmidt** [comment]
0.6 is out now
